# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 04:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=20)),
                ('time', models.DurationField()),
            ],
        ),
        migrations.CreateModel(
            name='Practice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.CharField(max_length=10)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField()),
                ('distance', models.IntegerField()),
                ('stroke', models.CharField(choices=[('fly', 'Butterfly'), ('back', 'Backstroke'), ('breast', 'Breaststroke'), ('free', 'Freestyle')], max_length=6)),
                ('comments', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repeats', models.IntegerField(blank=True)),
                ('practice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.Practice')),
            ],
        ),
        migrations.CreateModel(
            name='Swimmer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=25)),
                ('l_name', models.CharField(max_length=25)),
                ('gender', models.CharField(choices=[('F', 'female'), ('M', 'male')], max_length=1)),
                ('age', models.IntegerField(blank=True)),
                ('bio', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('abbr', models.CharField(max_length=5)),
                ('region', models.CharField(blank=True, max_length=25)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField()),
                ('end', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='swimmer',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.Team'),
        ),
        migrations.AddField(
            model_name='rep',
            name='set_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.Set'),
        ),
        migrations.AddField(
            model_name='practice',
            name='week',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.Week'),
        ),
        migrations.AddField(
            model_name='event',
            name='swimmer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.Swimmer'),
        ),
    ]
