# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-04 04:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_auto_20170703_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swimmer',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1),
        ),
    ]
