# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-07 16:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teams', '0003_auto_20170704_0053'),
    ]

    operations = [
        migrations.RenameField(
            model_name='practice',
            old_name='week',
            new_name='week_id',
        ),
        migrations.RenameField(
            model_name='set',
            old_name='practice',
            new_name='practice_id',
        ),
        migrations.RemoveField(
            model_name='practice',
            name='description',
        ),
        migrations.AddField(
            model_name='practice',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rep',
            name='rest',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='set',
            name='focus',
            field=models.CharField(blank=True, choices=[('sprint', 'Sprint'), ('mid-distance', 'Mid Distance'), ('distance', 'Distance')], max_length=10),
        ),
        migrations.AddField(
            model_name='set',
            name='order',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='practice',
            name='weekday',
            field=models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=10),
        ),
        migrations.AlterField(
            model_name='rep',
            name='comments',
            field=models.CharField(blank=True, max_length=254),
        ),
    ]
