# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-07 16:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_auto_20170707_1231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='practice',
            name='week_id',
        ),
    ]
