# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-07 22:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0005_remove_practice_week_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='set',
            name='repeats',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
