# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-08 20:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0007_auto_20170708_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rep',
            name='stroke',
            field=models.CharField(choices=[('fly', 'Butterfly'), ('back', 'Backstroke'), ('breast', 'Breaststroke'), ('free', 'Freestyle'), ('im', 'IM'), ('kick', 'Kick')], max_length=6),
        ),
        migrations.AlterField(
            model_name='set',
            name='focus',
            field=models.CharField(blank=True, choices=[('warmup', 'Warmup'), ('technique', 'Technique'), ('kick', 'Kick'), ('sprint', 'Sprint'), ('mid-distance', 'Mid Distance'), ('distance', 'Distance'), ('race', 'Race'), ('cooldown', 'Cooldown')], max_length=15),
        ),
    ]
