# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-09 00:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0008_auto_20170708_1648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='swimmer',
            name='age',
        ),
        migrations.AddField(
            model_name='swimmer',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
