# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-11 04:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0012_auto_20170709_2156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='week',
            name='user',
        ),
        migrations.AddField(
            model_name='week',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teams.Team'),
        ),
    ]
