# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-14 06:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0014_auto_20170712_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='swimmer',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
