# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-14 21:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0015_swimmer_age'),
    ]

    operations = [
        migrations.RenameField(
            model_name='week',
            old_name='current',
            new_name='present',
        ),
    ]
