# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-16 02:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0018_auto_20170715_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='set',
            name='focus',
            field=models.CharField(choices=[('warmup', 'Warmup'), ('technique', 'Technique'), ('kick', 'Kick'), ('sprint', 'Sprint'), ('mid-distance', 'Mid Distance'), ('distance', 'Distance'), ('race', 'Race'), ('cooldown', 'Cooldown')], max_length=15),
        ),
    ]
