# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-22 17:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0020_auto_20170722_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='set',
            name='swimmers',
            field=models.ManyToManyField(blank=True, to='teams.Swimmer'),
        ),
    ]
