# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-29 00:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0022_set_base'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='set',
            name='base',
        ),
        migrations.AddField(
            model_name='rep',
            name='base',
            field=models.CharField(choices=[('train', 'Base training Pace'), ('race', '100 Race Pace')], max_length=10, null=True),
        ),
    ]
