# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-29 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0024_auto_20170728_2058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='set',
            name='base',
        ),
        migrations.AddField(
            model_name='set',
            name='pace',
            field=models.CharField(choices=[('train', 'Base training pace'), ('race', '100 race pace')], max_length=10, null=True),
        ),
    ]
