# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-30 06:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0025_auto_20170729_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingmultiplier',
            name='multiplier',
            field=models.FloatField(null=True),
        ),
    ]
