# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-30 07:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0027_set_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DurationField()),
            ],
        ),
        migrations.AlterField(
            model_name='event',
            name='event',
            field=models.CharField(choices=[('50 free', '50 Freestyle'), ('100 free', '100 Freestyle'), ('200 free', '200 Freestyle'), ('500 free', '500 Freestyle'), ('1000 free', '1000 Freestyle'), ('50 back', '50 Backstroke'), ('100 back', '100 Backstroke'), ('200 back', '200 Backstroke'), ('50 breast', '50 Breaststroke'), ('100 breast', '100 Breaststroke'), ('200 breast', '200 Breaststroke'), ('50 fly', '50 Butterfly'), ('100 fly', '100 Butterfly'), ('200 fly', '200 Butterfly'), ('free', 'Freestyle Base'), ('back', 'Backstroke Base'), ('breaset', 'Breaststroke Base'), ('fly', 'Butterfly Base'), ('im', 'IM')], max_length=10),
        ),
        migrations.AlterField(
            model_name='rep',
            name='stroke',
            field=models.CharField(choices=[('fly', 'Butterfly'), ('back', 'Backstroke'), ('breast', 'Breaststroke'), ('free', 'Freestyle'), ('im', 'IM')], max_length=6),
        ),
        migrations.AddField(
            model_name='interval',
            name='rep',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.Rep'),
        ),
        migrations.AddField(
            model_name='interval',
            name='swimmer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.Swimmer'),
        ),
    ]
