# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-01 04:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0029_auto_20170731_2222'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['event', 'time']},
        ),
        migrations.AlterModelOptions(
            name='interval',
            options={'ordering': ['swimmer', 'rep', 'time']},
        ),
        migrations.AlterModelOptions(
            name='practice',
            options={'ordering': ['week_id']},
        ),
        migrations.AlterModelOptions(
            name='rep',
            options={'ordering': ['set_id', 'stroke']},
        ),
        migrations.AlterModelOptions(
            name='set',
            options={'ordering': ['practice_id', 'order']},
        ),
        migrations.AlterModelOptions(
            name='swimmer',
            options={'ordering': ['l_name', 'f_name']},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='trainingmultiplier',
            options={'ordering': ['training_model', 'focus']},
        ),
        migrations.AlterField(
            model_name='rep',
            name='stroke',
            field=models.CharField(choices=[('fly', 'Butterfly'), ('back', 'Backstroke'), ('breast', 'Breaststroke'), ('free', 'Freestyle'), ('IM', 'IM')], max_length=6),
        ),
    ]
