# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-04 13:53
from __future__ import unicode_literals

from django.db import migrations, models
import teams.validators


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0031_auto_20170801_0101'),
    ]

    operations = [
        migrations.AddField(
            model_name='swimmer',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='trainingmultiplier',
            name='multiplier',
            field=models.CharField(max_length=5, null=True, validators=[teams.validators.valid_pct]),
        ),
    ]
