# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-10 02:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0032_auto_20170804_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='place',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trainingmultiplier',
            name='multiplier',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
