A01V3      20Swimmers Only                 Hy-Tek, Ltd               7.0CHy-Tek, Ltd         252-633-517707312017                                    TM43    N81
C11NE      NENUSCNortheastern University       Northeastern                                                                    MA02115     USA               N64
D01NE  JR  Abel, Casey                 042396CAS*AB    0423199621F                                                                                           N74
D3042396CAS*ABEL               X FFFFFFFFFFFFF                                                                                                               N62
D01NE  FR  Alkislar, Ilayda            070498ILA*AL    0704199819F                                                                                           N86
D3070498ILA*ALKI               X FFFFFFFFFFFFF                                                                                                               N72
D01NE  FR  Angotti, Elisabeth          071098ELI*AN    0710199819F                                                                                           N67
D3071098ELI*ANGOLissy          X FFFFFFFFFFFFF                                                                                                               N74
D01NE  FR  Armstrong, Katie            052198KAT*AR    0521199819F                                                                                           N07
D3052198KAT*ARMS               X FFFFFFFFFFFFF                                                                                                               N82
D01NE  SO  Asai-Sarris, Ava            120996AVA*AS    1209199620F                                                                                           N46
D3120996AVA*ASAI               X FFFFFFFFFFFFF                                                                                                               N72
D01NE  JR  Banak, Carolyn              090595CAR*BA    0905199521F                                                                                           N95
D3090595CAR*BANA               X FFFFFFFFFFFFF                                                                                                               N62
D01NE  JR  Barlow, Emily               101195EMI*BA    1011199521F                                                                                           N65
D3101195EMI*BARL               X FFFFFFFFFFFFF                                                                                                               N72
D01NE  JR  Barnes, Connor              032296CON*BA    0322199621M                                                                                           N16
D3032296CON*BARN               X FFFFFFFFFFFFF                                                                                                               N72
D01NE  SR  Bartlett, Christopher       080294CHR*BA    0802199422M                                                                                           N09
D3080294CHR*BARTChris          X FFFFFFFFFFFFF                                                                                                               N64
D01NE  SR  Bauer, Matthew              061893MAT*BA    0618199324M                                                                                           N26
D3061893MAT*BAUE               X FFFFFFFFFFFFF                                                                                                               N72
D01NE  JR  Behar, Raphael              042196RAP*BE    0421199621M                                                                                           N95
D3042196RAP*BEHARudi           X FFFFFFFFFFFFF                                                                                                               N14
D01NE  JR  Berger, Halle               022996HAL*BE    0229199621F                                                                                           N55
D3022996HAL*BERG               X FFFFFFFFFFFFF                                                                                                               N72
D01NE  FR  Bissonnette, Noah           051898NOA*BI    0518199819M                                                                                           N47
D3051898NOA*BISS               X FFFFFFFFFFFFF                                                                                                               N82
D01NE  SO  Bloom, Allison              092597ALL*BL    0925199719F                                                                                           N26
D3092597ALL*BLOO               X FFFFFFFFFFFFF                                                                                                               N82
D01NE  SO  Bogatko, Dana               062897DAN*BO    0628199720F                                                                                           N65
D3062897DAN*BOGA               X FFFFFFFFFFFFF                                                                                                               N62
D01NE  SR  Chen, WenQin                100592WEN*CH    1005199224M                                                                                           N25
D3100592WEN*CHEN               X FFFFFFFFFFFFF                                                                                                               N72
D01NE  SO  Cheng, Yuhan                042396YUH*CH    0423199621M                                                                                           N45
D3042396YUH*CHENTommy          X FFFFFFFFFFFFF                                                                                                               N84
D01NE  FR  Coghlan, Kevin              040198KEV*CO    0401199819M                                                                                           N16
D3040198KEV*COGH               X FFFFFFFFFFFFF                                                                                                               N72
D01NE  SO  Coreno, Emma                040997EMM*CO    0409199720F                                                                                           N35
D3040997EMM*CORE               X FFFFFFFFFFFFF                                                                                                               N82
D01NE  FR  DeLiberti, Serena           100998SER*DE    1009199818F                                                                                           N17
D3100998SER*DELI               X FFFFFFFFFFFFF                                                                                                               N82
D01NE  FR  Dottinger, Matthew          040298MAT*DO    0402199819M                                                                                           N97
D3040298MAT*DOTT               X FFFFFFFFFFFFF                                                                                                               N92
D01NE  JR  Doyle, Charles              051696CHA*DO    0516199621M                                                                                           N06
D3051696CHA*DOYLLiam           X FFFFFFFFFFFFF                                                                                                               N14
D01NE  SO  Elmaarouf, Imran            090397IMR*EL    0903199719M                                                                                           N07
D3090397IMR*ELMA               X FFFFFFFFFFFFF                                                                                                               N82
D01NE  SO  Fleischer, Ryan             012197RYA*FL    0121199720M                                                                                           N66
D3012197RYA*FLEI               X FFFFFFFFFFFFF                                                                                                               N82
D01NE  FR  Foley, Megan                041198MEG*FO    0411199819F                                                                                           N35
D3041198MEG*FOLE               X FFFFFFFFFFFFF                                                                                                               N72
D01NE  SO  Fong, Hanalei               121297HAN*FO    1212199719F                                                                                           N65
D3121297HAN*FONG               X FFFFFFFFFFFFF                                                                                                               N72
D01NE  SO  Formica, Sydney             082597SYD*FO    0825199719F                                                                                           N86
D3082597SYD*FORM               X FFFFFFFFFFFFF                                                                                                               N92
D01NE  SO  Fritzinger, Katherine       121094BAI*FR    1210199422F                                                                                           N88
D3121094BAI*FRITBailey         X FFFFFFFFFFFFF                                                                                                               N84
D01NE  FR  Furuta, Ellie               060198ELL*FU    0601199819F                                                                                           N85
D3060198ELL*FURU               X FFFFFFFFFFFFF                                                                                                               N92
D01NE  SR  Galus, Brett                012795BRE*GA    0127199522M                                                                                           N45
D3012795BRE*GALU               X FFFFFFFFFFFFF                                                                                                               N72
D01NE  JR  Garber, Brennan             110995BRE*GA    1109199521M                                                                                           N36
D3110995BRE*GARB               X FFFFFFFFFFFFF                                                                                                               N72
D01NE  JR  Greene, Brady               032996BRA*GR    0329199621M                                                                                           N75
D3032996BRA*GREE               X FFFFFFFFFFFFF                                                                                                               N72
D01NE  SO  Gridley, Henry              092196HEN*GR    0921199620M                                                                                           N36
D3092196HEN*GRID               X FFFFFFFFFFFFF                                                                                                               N72
D01NE  JR  Harris, Gavin               040896GAV*HA    0408199621M                                                                                           N75
D3040896GAV*HARR               X FFFFFFFFFFFFF                                                                                                               N82
D01NE  JR  Haviland, Charles           102196CHA*HA    1021199620M                                                                                           N07
D3102196CHA*HAVICharlie        X FFFFFFFFFFFFF                                                                                                               N15
D01NE  JR  Heath, Kassidy              091695KAS*HE    0916199521F                                                                                           N16
D3091695KAS*HEAT               X FFFFFFFFFFFFF                                                                                                               N72
D01NE  SR  Hoang, Brandon              122594BRA*HO    1225199422M                                                                                           N06
D3122594BRA*HOAN               X FFFFFFFFFFFFF                                                                                                               N72
D01NE  JR  Jaisle, Kurt                073196KUR*JA    0731199621M                                                                                           N55
D3073196KUR*JAIS               X FFFFFFFFFFFFF                                                                                                               N92
D01NE  FR  Kenyon, Thomas              090996THO*KE    0909199620M                                                                                           N46
D3090996THO*KENY               X FFFFFFFFFFFFF                                                                                                               N92
D01NE  JR  Landon, Matthew             121193MAT*LA    1211199323M                                                                                           N56
D3121193MAT*LANDMatt           X FFFFFFFFFFFFF                                                                                                               N14
D01NE  SO  Laundry, Alexis             120397ALE*LA    1203199719F                                                                                           N66
D3120397ALE*LAUN               X FFFFFFFFFFFFF                                                                                                               N72
D01NE  JR  Lefler, Dillon              090996DIL*LE    0909199620M                                                                                           N16
D3090996DIL*LEFL               X FFFFFFFFFFFFF                                                                                                               N72
D01NE  SO  Lenney, Morgan              071296MOR*LE    0712199621F                                                                                           N36
D3071296MOR*LENN               X FFFFFFFFFFFFF                                                                                                               N92
D01NE  FR  Leopold, Anastasia          080398ANA*LE    0803199818F                                                                                           N67
D3080398ANA*LEOPAna            X FFFFFFFFFFFFF                                                                                                               N73
D01NE  JR  Lin, Brian                  100295BRI*LI    1002199521M                                                                                           N44
D3100295BRI*LIN*               X FFFFFFFFFFFFF                                                                                                               N62
D01NE  FR  Mack, Henry                 082898HEN*MA    0828199818M                                                                                           N05
D3082898HEN*MACK               X FFFFFFFFFFFFF                                                                                                               N72
D01NE  FR  Manetti, Tommaso            061698TOM*MA    0616199819M                                                                                           N27
D3061698TOM*MANE               X FFFFFFFFFFFFF                                                                                                               N82
D01NE  SR  McCollister, Andrew         103092AND*MC    1030199224M                                                                                           N97
D3103092AND*MCCO               X FFFFFFFFFFFFF                                                                                                               N62
D01NE  FR  McCord, Gregory             111896GRE*MC    1118199620M                                                                                           N46
D3111896GRE*MCCO               X FFFFFFFFFFFFF                                                                                                               N72
D01NE  JR  McCrobie, Trevor            020595TRE*MC    0205199522M                                                                                           N86
D3020595TRE*MCCR               X FFFFFFFFFFFFF                                                                                                               N82
D01NE  FR  McGann, Daniel              030398DAN*MC    0303199819M                                                                                           N75
D3030398DAN*MCGADan            X FFFFFFFFFFFFF                                                                                                               N53
D01NE  FR  Miller, Caroline            101198CAR*MI    1011199719F                                                                                           N86
D3101198CAR*MILL               X FFFFFFFFFFFFF                                                                                                               N72
D01NE  FR  Monasterio, Gabriela        050798GAB*MO    0507199819F                                                                                           N48
D3050798GAB*MONA               X FFFFFFFFFFFFF                                                                                                               N72
D01NE  SO  Movchan, Artem              090998ART*MO    0909199818M                                                                                           N46
D3090998ART*MOVC               X FFFFFFFFFFFFF                                                                                                               N92
D01NE  JR  Murphy, Christopher         092196CHR*MU    0921199620M                                                                                           N58
D3092196CHR*MURPChris          X FFFFFFFFFFFFF                                                                                                               N74
D01NE  FR  Niemi, Sarah                051598SAR*NI    0515199819F                                                                                           N45
D3051598SAR*NIEM               X FFFFFFFFFFFFF                                                                                                               N82
D01NE  FR  Nikopoulos, Katherine       070997KAT*NI    0709199720F                                                                                           N19
D3070997KAT*NIKO               X FFFFFFFFFFFFF                                                                                                               N82
D01NE  FR  Noble, Allison              111498ALL*NO    1114199818F                                                                                           N16
D3111498ALL*NOBL               X FFFFFFFFFFFFF                                                                                                               N72
D01NE  SO  Nozhenko, Katerina          101595KAT*NO    1015199521F                                                                                           N87
D3101595KAT*NOZH               X FFFFFFFFFFFFF                                                                                                               N92
D01NE  JR  O'Donnell, John             030695JOH*OD    0306199522M                                                                                           N06
D3030695JOH*ODON               X FFFFFFFFFFFFF                                                                                                               N82
D01NE  FR  Papes, Daniel               011698DAN*PA    0116199819M                                                                                           N65
D3011698DAN*PAPE               X FFFFFFFFFFFFF                                                                                                               N72
D01NE  JR  Perez, Matthew              111395MAT*PE    1113199521M                                                                                           N36
D3111395MAT*PEREMatt           X FFFFFFFFFFFFF                                                                                                               N24
D01NE  JR  Philbrick, Maya             020996MAY*PH    0209199621F                                                                                           N56
D3020996MAY*PHIL               X FFFFFFFFFFFFF                                                                                                               N82
D01NE  JR  Pinkes, Samantha            082896SAM*PI    0828199620F                                                                                           N07
D3082896SAM*PINK               X FFFFFFFFFFFFF                                                                                                               N92
D01NE  JR  Plummer, Abby               052195ABB*PL    0521199522F                                                                                           N65
D3052195ABB*PLUM               X FFFFFFFFFFFFF                                                                                                               N72
D01NE  SO  Regulapati, Veditha         021697VED*RE    0216199720F                                                                                           N18
D3021697VED*REGU               X FFFFFFFFFFFFF                                                                                                               N82
D01NE  JR  Renaud, Alice               070796ALI*RE    0707199621F                                                                                           N65
D3070796ALI*RENA               X FFFFFFFFFFFFF                                                                                                               N72
D01NE  SR  Shi, Eric                   062594ERI*SH    0625199423M                                                                                           N34
D3062594ERI*SHI*               X FFFFFFFFFFFFF                                                                                                               N62
D01NE  JR  Smolyar, Yonathan           122297YON*SM    1222199719M                                                                                           N77
D3122297YON*SMOLYoni           X FFFFFFFFFFFFF                                                                                                               N54
D01NE  SO  Soucy, Jessica              080196JES*SO    0801199620F                                                                                           N36
D3080196JES*SOUCJess           X FFFFFFFFFFFFF                                                                                                               N34
D01NE  JR  Thornton, David             071796DAV*TH    0717199621M                                                                                           N76
D3071796DAV*THOR               X FFFFFFFFFFFFF                                                                                                               N92
D01NE  SO  Toppazzini, Tara            063096TAR*TO    0630199621F                                                                                           N27
D3063096TAR*TOPP               X FFFFFFFFFFFFF                                                                                                               N92
D01NE  JR  Tou, Barbara                112194BAR*TO    1121199422F                                                                                           N25
D3112194BAR*TOU*Basia          X FFFFFFFFFFFFF                                                                                                               N34
D01NE  JR  Van Winkle, Shelbe          020595SHE*VA    0205199522F                                                                                           N17
D3020595SHE*VANW               X FFFFFFFFFFFFF                                                                                                               N82
Z01        02Successful Build on 07-31-2017  0  0   1   1    74    74    0     0     0                                                                       N46
